<a href="https://colab.research.google.com/github/priscaogu/Udemy-Machine-learning/blob/main/Copy_of_logistic_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Logistic Regression

## Importing the libraries

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [ ]:
dataset = pd.read_csv('weatherAUS.csv')


In [ ]:
dataset2=dataset.loc[(dataset['Location']=='Sydney'),['Temp3pm','WindSpeed3pm','Humidity3pm','Pressure3pm','RainTomorrow']]
    

In [ ]:
dataset3=dataset2.dropna()

In [ ]:
X = dataset3.iloc[:, :-1].values
y = dataset3.iloc[:, -1].values

In [ ]:
#encoding the dependent variable

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

## Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 1)

In [ ]:
print(X_train)

[[  33.9   19.    44.  1009.3]
 [  27.5   17.    58.  1012.1]
 [  17.8   31.    62.  1015.9]
 ...
 [  25.8   17.    66.  1017. ]
 [  18.2   19.    54.  1027.8]
 [  24.3   24.    70.  1020.3]]


## Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
print(X_train)

[[ 2.87785612 -0.03651674 -0.6653524  -0.97302113]
 [ 1.3881717  -0.30590969  0.19356521 -0.57064571]
 [-0.86963124  1.57984097  0.43897024 -0.02456478]
 ...
 [ 0.99247428 -0.30590969  0.68437527  0.13351128]
 [-0.77652596 -0.03651674 -0.05183982  1.68553077]
 [ 0.64332949  0.63696564  0.9297803   0.60773946]]


In [ ]:
print(X_test)

[[-0.79980228 -0.30590969  0.00951144  0.73707442]
 [ 2.41232974 -0.84469559 -2.32183635 -0.08204698]
 [ 0.10797416  0.09817974  0.07086269  0.19099349]
 ...
 [ 0.20107943 -0.57530264  0.25491647  0.23410514]
 [ 0.99247428  0.63696564  0.31626772  0.00417632]
 [ 0.01486888  0.90635859 -0.78805491  0.43529285]]


In [ ]:
print(y)

[1 1 1 ... 0 0 0]


## Training the Logistic Regression model on the Training set

In [ ]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=0, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

## Predicting a new result

In [ ]:
print(classifier.predict(sc.transform([[17.3,13,56,1017.4]])))

[0]


## Predicting the Test set results

In [ ]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


## Making the Confusion Matrix

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[595  21]
 [117  89]]


0.8321167883211679